language: node_js
node_js:
- 10
script:
-
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: QAdOQ2vGOpnilhPLUAmcabgylv5xKr7TTojKBR5zc2EBsKrHkEkZLeW+YLG23fM8jDdkfhQhHgkhQohb8ffwmUzB+aQ8mdmjhE/sv/tILq1B16GDPxM+bRgy1QT+sIG+s7MCHeIoSqR/XmoxufApeTLX6Zyhekq6T7aM7kkSsj9bXys7sOmNpkcFbCW0jOfMnSoamjn2o2BscxVk55bM1G0E4qFs6QIqG9NiG2PpAfW6l1qZg1yiNXXQxPqNtIrq0rShalcMe6tI30vUa4AzqvoB+DCQs9oQGmNKHFQdByMSJgO8DGWHXZx6Whrrczxo6wE9Yose8NrFgzyi0QFkGqFn3ZijWwqlATSaRCoSA08XyvUb8Piil7fbqzToGO/9PFWOvdI2MZiJqt9TadQET2uf+v8MEAB5P2fKdEJPTtX95iW0Nbyo7JGPcFOgACKOd/Rj3UAI0nOo2lV1hrEGByYeCA/ZS9/l65ogc44da0P8/xH6510w1agryv0afUgwpc7JK2Ozg9bjoA0tnehY6z77YFAw3nYYC2I67zGZcmgR60iCSts0apyvRHxiYzPVhG0i+nSq2dcf7sskMZbFB3aZZDROnvSooXBAgAszqVBuet639nEXSqTPk1SBqxfhZHtuqKtM9SVTiDOBV2HheAPJeNDXD1hyensV0vgMCic=
  app: avery-vine-server
  on:
    repo: AveryVine/PersonalServer
